api:
    enabled: true
    global_url: http://127.0.0.1:8080
    guard_password: ""
    host: 127.0.0.1
    mode: cloud
    port: 8080
    token: ""
collector:
    workers: 5
database:
    driver: sqlite
    name: vpsm
    path: /Users/sabbir/.local/share/vpsm/vpsm.db
    uri: mongodb://127.0.0.1:27017
logging:
    format: pretty
    level: info
plugins:
    enabled: true
ssh:
    timeout: 10s
